# Generated by Django 3.2.18 on 2023-04-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20230421_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../profile-avatar_omfvlb', upload_to='images/'),
        ),
    ]
