# Generated by Django 3.2.18 on 2023-03-20 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_rename_comments_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_reply_to_comment',
        ),
    ]
