# Generated by Django 3.2.18 on 2023-03-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_due_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=250, unique_for_date='due_date'),
        ),
    ]
