# Generated by Django 3.2.18 on 2023-03-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
