# Generated by Django 3.2.18 on 2023-04-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_task_shared_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.CharField(choices=[('overdue', 'Overdue'), ('to-do', 'To-do'), ('completed', 'Completed')], default='to-do', max_length=15),
        ),
    ]
