# Generated by Django 3.2.18 on 2023-04-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_task_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='datetime_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
