# Generated by Django 3.2.18 on 2023-04-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_task_datetime_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.CharField(choices=[('overdue', 'Overdue'), ('to-do', 'To-do'), ('completed', 'Completed')], max_length=15),
        ),
    ]
