# Generated by Django 3.2.18 on 2023-04-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_task_is_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=150, unique_for_date='due_date'),
        ),
    ]
