# Generated by Django 3.2.18 on 2023-03-20 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_tasks', '0002_alter_sharedtask_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharedtask',
            options={'ordering': ['-datetime_updated']},
        ),
    ]
