# Generated by Django 3.2.18 on 2023-03-21 01:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared_tasks', '0003_alter_sharedtask_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sharedtask',
            unique_together={('owner', 'task')},
        ),
    ]
