# Generated by Django 3.2.18 on 2023-03-23 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared_tasks', '0004_alter_sharedtask_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedtask',
            name='shared_to',
            field=models.ManyToManyField(related_name='shared', to=settings.AUTH_USER_MODEL),
        ),
    ]
