# Generated by Django 3.2.18 on 2023-03-23 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_tasks', '0005_alter_sharedtask_shared_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SharedTask',
        ),
    ]
